POST http://localhost:8080/contact_us
Content-Type: application/json

{
  "name": "my name",
  "email":"my email address",
  "phone": "dfa",
  "message": "aaa"
}

###
GET http://localhost:8080/stats
Accept: application/json

###
